### ISSUE TITLE
Mona test is not correct

### ISSUE THREAD

**Issue by hewigovens** [ensdomains/address-encoder#11]
https://github.com/ensdomains/address-encoder/blob/master/src/__tests__/index.test.ts#L61 is not a valid script, we have this: https://github.com/hewigovens/go-coincodec/blob/master/bitcoin_forks_test.go#L267

**Comment by Arachnid** [comment]
Can you clarify what's wrong with it? It was taken straight from https://github.com/wakiyamap/electrum-mona/blob/master/electrum_mona/tests/test_bitcoin.py#L362-#L376

**Comment by hewigovens** [comment]
hmm, blockbook explorer doesn't recognize it: https://blockbook.electrum-mona.org/address/mona1zw508d6qejxtdg4y5r3zarvaryvhm3vz7, so I wonder if it's valid user address

**Comment by wakiyamap** [comment]
Sorry for late reply.
This address(`mona1zw508d6qejxtdg4y5r3zarvaryvhm3vz7`) is witness v1 address.
`Blockbook` use `martinboehm/btcutil([btcsuite/btcutil](https://github.com/btcsuite/btcutil) fork)`.
This is not compatible with witness v1.
