### ISSUE TITLE
Library is too huge

### ISSUE THREAD

**Issue by petejkim** [ensdomains/address-encoder#24]
It pulls in several blockchain SDKs in their entirety, resulting in a huge bundle size (2MB+) even after minification. That makes it less ideal for embedding in web apps.

**Comment by JohnnyJumper** [comment]
Faced similar issue, any plans to reduce the size? It used to be 64KB now about 2MB+

**Comment by Arachnid** [comment]
https://github.com/ensdomains/address-encoder/issues/26
