### ISSUE TITLE
Review PRs for adding STX and RUNE, and updating IOTA

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/address-encoder#300]
https://github.com/ensdomains/address-encoder/pull/299

https://github.com/ensdomains/address-encoder/pull/298

**Comment by admljhnsn** [comment]
could the [iota support PR](https://github.com/ensdomains/address-encoder/pull/301) be added to this as well?

**Comment by makoto** [comment]
@brantlymillegan do you want to add a bounty to support  $ADA which has been broken for quite some time?
