### ISSUE TITLE
New IOTA address format not supported yet

### ISSUE THREAD

**Issue by MaKla89** [ensdomains/address-encoder#305]
While a record for an iota-address can be added it seems that the form is not up-to-date. IOTA did perform quite a fundamental upgrade in April 2021 and the address format has changed since.

The new specifications for the address format can be found in the [official documentation](https://chrysalis.docs.iota.org/guides/dev_guide#iota-15-address-anatomy) under `IOTA 1.5 (Chrysalis) address (bech32 standard): Mainnet with iota`

**Comment by admljhnsn** [comment]
I created a pull request for this update a few weeks ago, just waiting for them to merge it, see [here](https://github.com/ensdomains/address-encoder/pull/301).

**Comment by MaKla89** [comment]
> I created a pull request for this update a few weeks ago, just waiting for them to merge it, see [here](https://github.com/ensdomains/address-encoder/pull/301) also this issue [here](https://github.com/ensdomains/address-encoder/issues/300).

Oh perfect,  thank you and sorry that I did not see that :)
