### ISSUE TITLE
Add EVM compatible chains and rollups

### ISSUE THREAD

**Issue by makoto** [ensdomains/address-encoder#314]
(NOTE: This is outside of Gitcoin bounties until further notice)

- Polygon = symbol:MATIC, cointype: 966
- Binance Smart Chain = symbol: BSC, cointype: 519
- Arbitrum = symbol: ARB1, cointype: TBA
- Starkware
- ZKSync
- Aztec

**Comment by jefflau** [comment]
Polygon Hermez
