### ISSUE TITLE
Change EVM compatible chains to use `convertEVMChainIdToCoinType(chainId)` instead of coinType

### ISSUE THREAD

**Issue by makoto** [ensdomains/address-encoder#318]
Currently `ARB1` is the only EVM compatible chain that uses `convertEVMChainIdToCoinType(chainId)`.

Convert all other evm compatible chains (listed below) as well as add other prominent EVM chains.

```
makoto@makoto-1:~/work/address-encoder$ grep hexCheck src/index.ts 
const hexChecksumChain = (name: string, coinType: number, chainId?: number) => ({
  hexChecksumChain('ETH', 60),
  hexChecksumChain('ETC', 61),
  hexChecksumChain('RSK', 137, 30),
  hexChecksumChain('POA', 178),
  hexChecksumChain('EWT', 246),
  hexChecksumChain('THETA', 500),
  hexChecksumChain('BSC', 519),
  hexChecksumChain('TFUEL', 589),
  hexChecksumChain('OPT', 614),
  hexChecksumChain('XDAI', 700),
  hexChecksumChain('VET', 703),
  hexChecksumChain('CLO', 820),
  hexChecksumChain('TOMO', 889),
  hexChecksumChain('MATIC', 966),
  hexChecksumChain('TT', 1001),
  hexChecksumChain('FTM', 1007),
  hexChecksumChain('GO', 6060),
  hexChecksumChain('NRG', 9797),
  hexChecksumChain('CELO', 52752),
```

**Comment by briansoule** [comment]
+ AVAX

**Comment by makoto** [comment]
closing the issue as the earlier version had a bug. Will reopen once fixed

**Comment by makoto** [comment]
AVAX (and Harmony) are tricky ones as it allows multiple formats and EVM compatible ones are one of the accepted format. Currently AVAX is set as hex32 and already in the repo

**Comment by briansoule** [comment]
Yeah I'd assume that AVAX C-Chain would be treated as it's own network?

**Comment by briansoule** [comment]
We have a similar situation with Binance Chain and Binance Smart Chain

**Comment by briansoule** [comment]
Additionally they use BNB and AVAX coins respectively for all of their chains
