### ISSUE TITLE
Failed to resolve entry for package "'crypto-addr-codec" when using Vite to build projects

### ISSUE THREAD

**Issue by mozwell** [ensdomains/address-encoder#379]
One of our projects use @ensdomains/address-encoder as one of its dependencies.

When using Vite to build projects, there is an error message shown as follows:
![image](https://user-images.githubusercontent.com/59408225/221331588-40da5296-f771-4307-b8c9-68708da8e312.png)

After investigation, it seems like `crypto-addr-codec` has a strange entry point for ESM. The temporary fix is to change package.json in crypto-addr-codec, and make "module" as "lib/index.js". Given that `crypto-addr-codec` has been out of maintenance for a long time, I think the best strategy is to fork that, fix the entry point, and then make it as the correct dependency used in  @ensdomains/address-encoder.

**Comment by Ivan-dev-RED** [comment]
I have the same problem...

**Comment by zgayjjf** [comment]
I saw the repo `crypto-addr-codec` is not maintained. 
It would be great if anyone can fix it. It just needs a little work.@makoto 

https://github.com/ensdomains/crypto-addr-serialize/issues/17
