### ISSUE TITLE
Security issue: Non-secure cryptography is used, switch to audited libraries

### ISSUE THREAD

**Issue by paulmillr** [ensdomains/address-encoder#384]
```
    "bech32": "^2.0.0",
    "blakejs": "^1.1.0",
    "bs58": "^4.0.1",
    "js-sha256": "^0.9.0",
    "js-sha512": "^0.8.0",
    "nano-base32": "^1.0.1",
    "ripemd160": "^2.0.2",
    "sha3": "^2.1.3"
```

All of those can be replaced with audited noble-hashes and scure-base, which have been audited by funding from Ethereum Foundation and are included in github.com/ethereum/js-etheruem-cryptography.

Current libraries pose much higher risk to users.

**Comment by ukstv** [comment]
I decided to address hashing part in https://github.com/ensdomains/address-encoder/pull/388 :D
