### ISSUE TITLE
Add support for FIL addresses

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/address-encoder#85]
https://spec.filecoin.io/#appendix__address

We have a grant from Protocol Labs to do this, so please keep me updated.

**Comment by developerfred** [comment]
I will work on this issue

**Comment by brantlymillegan** [comment]
> I will work on this issue

Are you wanting a bounty for this? I don't currently have this listed on Gitcoin

**Comment by developerfred** [comment]
@brantlymillegan It would be great, I will do the PR and sign up for the available Gitcoin Bountys.

**Comment by brantlymillegan** [comment]
> @brantlymillegan It would be great, I will do the PR and sign up for the available Gitcoin Bountys.

Thanks but I think we'll work on this one internally. Feel free to work on any of the many bounties we have set up
